eda:
  sample_rows: 5000   
features:
  distances: [haversine, manhattan, bearing]
  time_parts: [hour, weekday, month, is_weekend, is_rush_hour]
model:
  target: trip_duration
  metrics: [rmse, mae]
